### ISSUE TITLE
minor mistake in doc

### ISSUE THREAD

**Issue by asteriogonzalez** [ftao/python-ifcfg#12]
I think when you say in the doc

`for interface in ifcfg.interfaces:
`

it must be something like:

`for name, interface in ifcfg.interfaces().items():
`

or

`for interface in ifcfg.interfaces().values():
`

as is a function and returns a dict() instead a list

**Comment by benjaoming** [comment]
Thanks for reporting this @asteriogonzalez !

Would you be able to submit a PR for this? It would be very helpful :+1:
