### ISSUE TITLE
Character \x84 causing issues

### ISSUE THREAD

**Issue by benjaoming** [ftao/python-ifcfg#17]
In 0.12, we are now facing this bug on localized versions of Windows w Python 2.7:

```
  File "c:\python27\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Python27\Scripts\kolibri.exe\__main__.py", line 9, in <module>
  File "c:\python27\lib\site-packages\kolibri\utils\cli.py", line 592, in main
    start(port, daemon=daemon)
  File "c:\python27\lib\site-packages\kolibri\utils\cli.py", line 263, in start
    __, urls = server.get_urls(listen_port=port)
  File "c:\python27\lib\site-packages\kolibri\utils\server.py", line 297, in get_urls
    interfaces = ifcfg.interfaces()
  File "c:\python27\lib\site-packages\kolibri\dist\ifcfg\__init__.py", line 68, in interfaces
    return Parser(ifconfig=ifconfig).interfaces
  File "c:\python27\lib\site-packages\kolibri\dist\ifcfg\parser.py", line 29, in __init__
    self.parse(self.ifconfig_data)
  File "c:\python27\lib\site-packages\kolibri\dist\ifcfg\parser.py", line 53, in parse
    ifconfig, __, __ = exec_cmd(self.get_command())
  File "c:\python27\lib\site-packages\kolibri\dist\ifcfg\tools.py", line 39, in exec_cmd
    stdout = stdout.encode("utf-8").decode(system_encoding, errors='replace')
  File "c:\python27\lib\encodings\utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0x84 in position 85: invalid start byte```
```

**Comment by benjaoming** [comment]
I can sort of reproduce this in Python 2 by doing this:

```
>>> binascii.unhexlify("84").decode("utf-8")

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0x84 in position 0: invalid start byte
```

Replacing works though:

```
>>> binascii.unhexlify("84").decode("utf-8", errors="replace")
u'\ufffd'
```

This is super lame, because the failed call already has `errors="replace"`, so in that sense, I still can't reproduce the nature of this :/

**Comment by ftao** [comment]
I think the problem is 
 https://github.com/ftao/python-ifcfg/blob/3ddb52e97cb13b2ba0d8792252b4aab2be55096b/src/ifcfg/tools.py#L28
"    # Using `universal_newlines=True` because we want string output, not bytes" this is wrong .. 

Even if you set universal_newlines = True, the stdout, stderr is still "str" not "unicode" . 


What happens here is 
`stdout = stdout.encode("utf-8").decode(system_encoding, errors='replace')`
the first  stdout.encode ->  stdout.decode(default_system_encoding).encode('utf-8') will throw the error .

**Comment by benjaoming** [comment]
@ftao could you be more specific about what you think throws the error? From the traceback in the report, it seems that the last call to `decode` throws the error, and this is what I fail to find a way to reproduce.

I don't see what `universal_newlines=True` would fix, my code comment doesn't seem to contradict what you observe?

**Comment by ftao** [comment]
I means no matter what you set for  `universal_newlines`,  stdout, stderr is  "bytes" not "string". 
so when you call 
```stdout.encode('utf-8')``` ,  what actually happen is 
```stdout.decode(sys.getdefaultencoding()).encode('utf-8')```

I thinkthe correctly way is just 
```
stdout = stdout.decode(system_encoding, errors='replace')
```

**Comment by benjaoming** [comment]
Thanks for the advice @ftao - I think you might have been very spot on about the implicit call to `decode`, although it still baffles me :) Asides from that, I had to deal with Python 2 and 3 differing with stdout/stderr being `string` and `bytestring`, respectively. I think it's all good now, had a :+1: from the reporter that it was tested on a German Windows that originally produced the issue.
