### ISSUE TITLE
New PyPi maintainer

### ISSUE THREAD

**Issue by benjaoming** [ftao/python-ifcfg#54]
To reduce bus-factor, I have invited @lyw07 as co-maintainer of releases on PyPi. Previously, I was the only maintainer on that project, yikes. We work for the same organization, so I naturally vouch for this :100: 

@ftao should you wish to have PyPi access, LMK your username there. I also think itd be great if you could give @lyw07 repo access?

**Comment by lyw07** [comment]
thank you @benjaoming and @ftao for inviting me to the repo and PyPI!

**Comment by benjaoming** [comment]
Awesome, closing this, glad to see this project still maintained :)

**Comment by benjaoming** [comment]
Reopening to flag that @jonboiser was added on PyPi, he is also part of @learningequality and has experience maintaining Python packages. @ftao if you add him as well to the git repo, we are bolstered.

**Comment by ftao** [comment]
invited @jonboiser

**Comment by benjaoming** [comment]
Thanks @ftao :pray:
