### ISSUE TITLE
Support Gateways

### ISSUE THREAD

**Issue by 5t4cktr4c3** [ftao/python-ifcfg#59]
Is it possible to support getting information about the gateways for the linux parser?

**Comment by benjaoming** [comment]
Thanks for filling in this issue.

IMHO, this is within the scope of the project.

If you want gateway information, you can run `route` (legacy) or `ip route list` but this project is originally only intended for `ifconfig` and later `ip addr show`, none of which have gateway information AFAIK.

Ideally, we would have everything work cross-platform, so implementing this only for Linux-based platforms would also be a bit of a stretch.

I would say that if you can

**Comment by 5t4cktr4c3** [comment]
I would only be able to implement this feature for Linux via `ip route`, since I'm not familiar with networking in Windows. Are you nevertheless interested in a PR?

**Comment by benjaoming** [comment]
I think if you can contribute that PR, you could potentially make the structure necessary for someone to add a Windows solution. But you could potentially write the Windows solution, too? It seems trivial if you write it for the example output here:

https://github.com/ftao/python-ifcfg/blob/master/tests/ipconfig_out.py
