### ISSUE TITLE
inet is not populated when returning the ip address with an arrow notation (-->)

### ISSUE THREAD

**Issue by aaronwarshay** [ftao/python-ifcfg#71]
Hi,

I have a case where the inet value was being returned ok in version 0.22, but fails to populate when using version 0.23:

```
utun3: flags=8051<UP,POINTOPOINT,RUNNING,MULTICAST> mtu 1500
	inet 10.11.11.72 --> 10.11.11.72 netmask 0xffffff00 
```

It occurs in macOS using an OpenVPN connection.  Will you please investigate a fix for this case?

Regards,

-A

**Comment by benjaoming** [comment]
Hi @aaronwarshay 

The error probably happened here: https://github.com/ftao/python-ifcfg/pull/67/files#diff-231f8ffbdb82aebe14681a88db72af3a09c3788200e3ab097e3de89d7a4561dbR245

If you can figure out a new regex that works, please go ahead and submit a PR :+1: 

Ultimately, this repo needs some CI :)
